NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NCountry.PS_IMPROVE_PROVINCE_BASE = 45
NDefines.NEconomy.BANKRUPTCY_BUILDING_DESTRUCTION_THRESHOLD = 7
NDefines.NMilitary.CAVALRY_SPEED = 1.05
NDefines.NMilitary.DAYS_PER_PHASE = 2
NDefines.NMilitary.MERCENARY_COMPANY_MAX_REGIMENTS = 40